# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"init": "http-adapter.ipynb",
         "get_data": "http-adapter.ipynb",
         "respond": "http-adapter.ipynb",
         "app": "http-adapter.ipynb",
         "STATE": "http-adapter.ipynb",
         "debug_print": "multiprocess-bot.ipynb",
         "get_chained_data": "multiprocess-bot.ipynb",
         "set_chained_data": "multiprocess-bot.ipynb",
         "tryint": "multiprocess-bot.ipynb",
         "CHAT_RET": "multiprocess-bot.ipynb",
         "Pipe": "multiprocess-bot.ipynb",
         "Segment": "multiprocess-bot.ipynb",
         "ValidatedSegment": "multiprocess-bot.ipynb",
         "MultiChoiceSegment": "multiprocess-bot.ipynb",
         "ComputeSegment": "multiprocess-bot.ipynb",
         "Composite": "multiprocess-bot.ipynb",
         "LoopComposite": "multiprocess-bot.ipynb",
         "TextAdapter": "multiprocess-bot.ipynb",
         "Splitter": "multiprocess-bot.ipynb",
         "SkipSplitter": "multiprocess-bot.ipynb"}

modules = ["httpadapter.py",
           "flowchatbot.py"]

doc_url = "https://kulkarniniraj.github.io/flowchatbot/"

git_url = "https://github.com/kulkarniniraj/flowchatbot/tree/master/"

def custom_doc_links(name): return None
